// <auto-generated>
// This code was auto-generated by a tool, every time
// the tool executes this code will be reset.
//
// If you need to extend the classes generated to add
// fields or methods to them, please create partial
// declarations in another file.
// </auto-generated>
#pragma warning disable 0109
#pragma warning disable 1591


namespace Quantum.Prototypes.Unity {
  using Photon.Deterministic;
  using Quantum;
  using Quantum.Core;
  using Quantum.Collections;
  using Quantum.Inspector;
  using Quantum.Physics2D;
  using Quantum.Physics3D;
  using Byte = System.Byte;
  using SByte = System.SByte;
  using Int16 = System.Int16;
  using UInt16 = System.UInt16;
  using Int32 = System.Int32;
  using UInt32 = System.UInt32;
  using Int64 = System.Int64;
  using UInt64 = System.UInt64;
  using Boolean = System.Boolean;
  using String = System.String;
  using Object = System.Object;
  using FlagsAttribute = System.FlagsAttribute;
  using SerializableAttribute = System.SerializableAttribute;
  using MethodImplAttribute = System.Runtime.CompilerServices.MethodImplAttribute;
  using MethodImplOptions = System.Runtime.CompilerServices.MethodImplOptions;
  using FieldOffsetAttribute = System.Runtime.InteropServices.FieldOffsetAttribute;
  using StructLayoutAttribute = System.Runtime.InteropServices.StructLayoutAttribute;
  using LayoutKind = System.Runtime.InteropServices.LayoutKind;
  #if QUANTUM_UNITY //;
  using TooltipAttribute = UnityEngine.TooltipAttribute;
  using HeaderAttribute = UnityEngine.HeaderAttribute;
  using SpaceAttribute = UnityEngine.SpaceAttribute;
  using RangeAttribute = UnityEngine.RangeAttribute;
  using HideInInspectorAttribute = UnityEngine.HideInInspector;
  using PreserveAttribute = UnityEngine.Scripting.PreserveAttribute;
  using FormerlySerializedAsAttribute = UnityEngine.Serialization.FormerlySerializedAsAttribute;
  using MovedFromAttribute = UnityEngine.Scripting.APIUpdating.MovedFromAttribute;
  using CreateAssetMenu = UnityEngine.CreateAssetMenuAttribute;
  using RuntimeInitializeOnLoadMethodAttribute = UnityEngine.RuntimeInitializeOnLoadMethodAttribute;
  #endif //;
  
  [System.SerializableAttribute()]
  public unsafe partial class AIBlackboardComponentPrototype : Quantum.QuantumUnityPrototypeAdapter<Quantum.Prototypes.AIBlackboardComponentPrototype> {
    public AssetRef<AIBlackboard> Board;
    [DictionaryAttribute()]
    [DynamicCollectionAttribute()]
    public Quantum.Prototypes.Unity.DictionaryEntry_Int32_BlackboardEntry[] Entries = {};
    partial void ConvertUser(Quantum.QuantumEntityPrototypeConverter converter, ref Quantum.Prototypes.AIBlackboardComponentPrototype prototype);
    public override Quantum.Prototypes.AIBlackboardComponentPrototype Convert(Quantum.QuantumEntityPrototypeConverter converter) {
      var result = new Quantum.Prototypes.AIBlackboardComponentPrototype();
      converter.Convert(this.Board, out result.Board);
      converter.Convert(this.Entries, out result.Entries);
      ConvertUser(converter, ref result);
      return result;
    }
  }
  [System.SerializableAttribute()]
  public unsafe partial class BlackboardEntryPrototype : Quantum.QuantumUnityPrototypeAdapter<Quantum.Prototypes.BlackboardEntryPrototype> {
    public Quantum.Prototypes.Unity.BlackboardValuePrototype Value;
    partial void ConvertUser(Quantum.QuantumEntityPrototypeConverter converter, ref Quantum.Prototypes.BlackboardEntryPrototype prototype);
    public override Quantum.Prototypes.BlackboardEntryPrototype Convert(Quantum.QuantumEntityPrototypeConverter converter) {
      var result = new Quantum.Prototypes.BlackboardEntryPrototype();
      converter.Convert(this.Value, out result.Value);
      ConvertUser(converter, ref result);
      return result;
    }
  }
  [System.SerializableAttribute()]
  public unsafe partial class BlackboardValuePrototype : Quantum.QuantumUnityUnionPrototypeAdapter<Quantum.Prototypes.BlackboardValuePrototype> {
    public string _field_used_;
    public QBoolean BooleanValue;
    public Byte ByteValue;
    public Int32 IntegerValue;
    public FP FPValue;
    public FPVector2 FPVector2Value;
    public FPVector3 FPVector3Value;
    public Quantum.QuantumEntityPrototype EntityRefValue;
    public AssetRef AssetRefValue;
    partial void ConvertUser(Quantum.QuantumEntityPrototypeConverter converter, ref Quantum.Prototypes.BlackboardValuePrototype prototype);
    public override Quantum.Prototypes.BlackboardValuePrototype Convert(Quantum.QuantumEntityPrototypeConverter converter) {
      var result = new Quantum.Prototypes.BlackboardValuePrototype();
      converter.Convert(this._field_used_, out result._field_used_);
      converter.Convert(this.BooleanValue, out result.BooleanValue);
      converter.Convert(this.ByteValue, out result.ByteValue);
      converter.Convert(this.IntegerValue, out result.IntegerValue);
      converter.Convert(this.FPValue, out result.FPValue);
      converter.Convert(this.FPVector2Value, out result.FPVector2Value);
      converter.Convert(this.FPVector3Value, out result.FPVector3Value);
      converter.Convert(this.EntityRefValue, out result.EntityRefValue);
      converter.Convert(this.AssetRefValue, out result.AssetRefValue);
      ConvertUser(converter, ref result);
      return result;
    }
  }
  [System.SerializableAttribute()]
  public unsafe partial class DictionaryEntry_Int32_BlackboardEntry : Quantum.Prototypes.DictionaryEntry, Quantum.IQuantumPrototypeConvertible<Quantum.Prototypes.DictionaryEntry_Int32_BlackboardEntry> {
    public Int32 Key;
    public Quantum.Prototypes.Unity.BlackboardEntryPrototype Value;
    public Quantum.Prototypes.DictionaryEntry_Int32_BlackboardEntry Convert(Quantum.QuantumEntityPrototypeConverter converter) {
      var result = new Quantum.Prototypes.DictionaryEntry_Int32_BlackboardEntry();
      converter.Convert(Key, out result.Key);
      converter.Convert(Value, out result.Value);
      return result;
    }
  }
}
#pragma warning restore 0109
#pragma warning restore 1591
